### ISSUE TITLE
[BUG] Remove node_modules directory

### ISSUE THREAD

**Issue by vikasganiga05** [NoelleKuti/Jobify#1]
I think you forgot to remove the `node_modules` directory from the repo. Follow the below steps to remove and ignore the `node_modules` directory :point_down: 

Make sure you in the root of this project before running the below commands in the terminal.

```bash
# Remove the node_modules directory from git but not delete it from the filesystem/locally.
git rm -r --cached node_modules

# Commit the changes
git commit -m "Remove and ignore node_modules directory"

# Push the changes
git push origin main
```

This blog post explained it easily &rarr; [What to do if you accidentally committed your node_modules](https://dev.to/momentum/what-to-do-if-you-accidentally-committed-your-nodemodules-323o)

**Comment by NoelleKuti** [comment]
I appreciate this so much! Hopefully it's fixed now, let me know if not (still getting the hang of github lol)

**Comment by vikasganiga05** [comment]
> I appreciate this so much! Hopefully it's fixed now, let me know if not (still getting the hang of github lol)

Yes, it fixed well done :+1:

**Comment by vikasganiga05** [comment]
I also did this when I was started learning git & github :sweat_smile:
